owner: "openeuler-ci-bot"
repository: "https://gitee.com/openeuler/website"
giteeToken: ""
webhookSecret: ""
databaseType: "mysql"
databaseHost: "127.0.0.1"
databasePort: 3306
databaseName: "cibot"
databaseUserName": "******"
databasePassword": "******"
