owner: "openeuler-ci-bot"
repository: "https://gitee.com/openeuler/website"
giteeToken: "******"
webhookSecret: "******"
databaseType: "mysql"
databaseHost: "127.0.0.1"
databasePort: 3306
databaseName: "cibot"
databaseUserName: "root"
databasePassword: "******"
watchProjectFileOwner: openeuler
watchprojectFileRepo: ci-bot
watchprojectFilePath: projects.yaml
watchProjectFileRef: master
watchProjectFileDuration: 60
