giteeToken: "******"
webhookSecret: "******"
databaseType: "mysql"
databaseHost: "127.0.0.1"
databasePort: 3306
databaseName: "cibot"
databaseUserName: "root"
databasePassword: "******"
#the flag that pull request commit_id has changed
prUpdateLabelFlag: "source_branch_changed"
#List of labels that need to be deleted after the commit_id is changed
delLabels:
  - lgtm
  - approve
  - priority
  - openeuler-cla
  - sig
  - kind
lgtmCountsRequired: 1
requiringLabels:
- openeuler-cla/yes
missingLabels:
- do-not-merge
watchProjectFiles:
  - watchProjectFileOwner: openeuler
    watchprojectFileRepo: infrastructure
    watchprojectFilePath: repository/openeuler.yaml
    watchProjectFileRef: master
  - watchProjectFileOwner: openeuler
    watchprojectFileRepo: infrastructure
    watchprojectFilePath: repository/src-openeuler.yaml
    watchProjectFileRef: master
watchProjectFileDuration: 60
watchSigFiles:
  - watchSigFileOwner: openeuler
    watchSigFileRepo: community
    watchSigFilePath: sig/sigs.yaml
    watchSigFileRef: master
watchSigFileDuration: 60
watchOwnerFiles:
  - watchOwnerFileOwner: openeuler
    watchOwnerFileRepo: community
    watchOwnerFilePath: sig/*/OWNERS
    watchOwnerFileRef: master
watchOwnerFileDuration: 300
botName: openeuler-ci-bot
communityName: openEuler
claLink: https://openeuler.org/en/cla.html
commandLink: https://gitee.com/openeuler/community/blob/master/en/sig-infrastructure/command.md
contactEmail: contact@openeuler.org
accordingfile: "src-openeuler.yaml"
newfileowner: "src-openeuler"
newfilerepo: "obs_meta"
newfilebranch: "master"
tmpservicefile: "_service"
tmpservicepath: "master/openEuler:Factory/#projectname#/_service"
guideurl: "https://gitee.com/openeuler/community/tree/master/zh/contributors"
